import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Web3Modal } from "@/components/web3-modal";
import { NavBar } from "@/components/nav-bar";
import JotaiProviders from "@/components/jotai-provider";
import { fetchInitialState } from "@/lib/api/market";
import { cookieToInitialState } from "wagmi";
import { headers } from "next/headers";
import { wagmiConfig } from "@/lib/config/wagmi";

const inter = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialWagmiState = cookieToInitialState(
    wagmiConfig,
    headers().get("cookie")
  );

  const state = await fetchInitialState(initialWagmiState);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Modal initialState={initialWagmiState}>
          <JotaiProviders initialState={state}>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <NavBar />
              {children}
            </ThemeProvider>
          </JotaiProviders>
        </Web3Modal>
      </body>
    </html>
  );
}
